version: '3.9'

services:
  frontend:
    image: ghcr.io/sallykalm/frontend-meowster-thesis:latest
    ports:
      - '80:80'
    depends_on:
      - backend

  backend:
    image: ghcr.io/scionova/four_philosopher_core:latest
    ports:
      - '15567:15567'
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
